### ISSUE TITLE
Exception caught:  TypeError: param.trim is not a function

### ISSUE THREAD

**Issue by varundeva** [paytm/paytm-pg-node-sdk#5]
```
Exception caught:  TypeError: param.trim is not a function
    at Function.isEmptyOrNull (/home/freesv/Desktop/BUDonation/node_modules/paytm-pg-node-sdk/dist/com/paytm/pg/utils/CommonUtil.js:71:81)
    at new PaymentDetailBuilder (/home/freesv/Desktop/BUDonation/node_modules/paytm-pg-node-sdk/dist/com/paytm/merchant/models/PaymentDetail.js:201:36)
    at payment.doPayment (/home/freesv/Desktop/BUDonation/app.js:68:40)
    at /home/freesv/Desktop/BUDonation/app.js:28:9
    at Layer.handle [as handle_request] (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/layer.js:95:5)
    at /home/freesv/Desktop/BUDonation/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/freesv/Desktop/BUDonation/node_modules/express/lib/router/index.js:335:12)
```

**Comment by vc-shruti** [comment]
Error [MongooseError]: TypeError: param.trim is not a function
    at new MongooseError (C:\Users\ShrutiS\Documents\abctalkies-api\node_modules\mongoose\lib\error\mongooseError.js:10:11)
    at Object.payNowByPayTm (C:\Users\ShrutiS\Documents\abctalkies-api\build\Controllers\PuchaseHistoryController.js:232:21)
    at C:\Users\ShrutiS\Documents\abctalkies-api\build\Routes\v1\PurchaseHistoryRouter.js:43:59
    at Layer.handle [as handle_request] (C:\Users\ShrutiS\Documents\abctalkies-api\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ShrutiS\Documents\abctalkies-api\node_modules\express\lib\router\route.js:137:13)
    at authenticate (C:\Users\ShrutiS\Documents\abctalkies-api\build\core\Authentication.js:33:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by pnutmath** [comment]
@paytm expecting `txnAmount` value in string

Seems this package is no longer being maintained. Can you please confirm @ravindrapaytm @pgpautomation
